import { ArrowUpRight, Code2, ExternalLink, Layers3 } from "lucide-react";
import Link from "next/link";
import { projects } from "@/data/projects";
import { SectionHeading } from "./SectionHeading";

export function Projects() {
  const groups = [{ type: "personal" as const, title: "Proyectos personales" }, { type: "professional" as const, title: "Proyectos profesionales" }];
  return <section id="proyectos" className="section border-b border-line/70"><div className="container"><SectionHeading number="03" eyebrow="Proyectos" title="Proyectos destacados" />{groups.map((group) => <div className="mb-12 last:mb-0" key={group.type}><h3 className="eyebrow mb-5">{group.title}</h3><div className="grid gap-6 lg:grid-cols-2">{projects.filter((project) => project.type === group.type).map((project, index) => <article className={`project-card ${group.type === "personal" ? "lg:col-span-2" : ""}`} key={project.slug}><div className="flex flex-col justify-between gap-6 p-6 sm:p-8"><div><span className="eyebrow">{String(index + 1).padStart(2, "0")} / {project.context}</span><h3 className="heading-card mt-2 text-xl">{project.title}</h3>{project.technicalName && <p className="mt-2 font-mono text-xs text-brand">{project.technicalName}</p>}<p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">{project.description}</p><div className="mt-5 flex flex-wrap gap-2">{project.technologies.map((technology) => <span className="tag" key={technology}>{technology}</span>)}</div></div><div className="flex flex-wrap items-center gap-4 border-t border-line/60 pt-4 text-xs font-semibold">{project.githubUrl ? <a className="inline-flex items-center gap-1 text-brand hover:text-white" href={project.githubUrl} target="_blank" rel="noreferrer">Ver código <Code2 size={14} /></a> : <span className="text-slate-500">Código pendiente de configurar</span>}{project.demoUrl ? <a className="inline-flex items-center gap-1 text-slate-400 hover:text-white" href={project.demoUrl} target="_blank" rel="noreferrer">Demo <ExternalLink size={14} /></a> : <span className="text-slate-500">Demo pendiente de configurar</span>}<Link className="ml-auto inline-flex items-center gap-1 text-brand hover:text-white" href={`/proyectos/${project.slug}`}>Ver proyecto <ArrowUpRight size={14} /></Link></div></div><div className="project-visual"><Layers3 size={25} /><span>{project.title}</span><small>{project.type === "personal" ? "Proyecto personal" : "Proyecto profesional"}</small></div></article>)}</div></div>)}</div></section>;
}
